# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "daf5c07e016538106bb21f43c6d379d1"
name = "offers-store"
handle = "offers-store"
application_url = "https://1f46-2405-201-ac0b-30e3-244d-9826-4773-aa8f.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-aeedc0e5.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://1f46-2405-201-ac0b-30e3-244d-9826-4773-aa8f.ngrok-free.app/auth/callback",
  "https://1f46-2405-201-ac0b-30e3-244d-9826-4773-aa8f.ngrok-free.app/auth/shopify/callback",
  "https://1f46-2405-201-ac0b-30e3-244d-9826-4773-aa8f.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
